# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "test"
  - "release"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  test:
    type: parallel
    steps:
      test_lib:
        title: "Test Surround Library"
        type: "freestyle" # Run any command
        image: "python:3.6.10" # The image in which command will be executed
        working_directory: "${{clone}}"
        commands:
          # Go inside the surround library
          - cd surround

          # Install surround
          - python3 setup.py install

          # Run tests
          - python3 setup.py test

          # Run pylint tests
          - pip install pylint==2.4.3
          - pylint setup.py
          - find surround/ -iname "*.py" | xargs pylint
        stage: "test"

      test_cli:
        title: "Test Surround CLI"
        type: "freestyle" # Run any command
        image: "python:3.6.10" # The image in which command will be executed
        working_directory: "${{clone}}"
        commands:
          # Go inside the cli
          - cd surround-cli

          # Install surround
          - python3 setup.py install

          # Run tests
          - python3 setup.py test

          # Run pylint tests
          - pip install pylint==2.4.3
          - pylint setup.py
          - find surround_cli/ -iname "*.py" | xargs pylint

          # Run examples
          - cd ..
          - find examples/ -iname "*.py" | xargs pylint
          - ls examples/ | xargs -n 1 -I '{}' python3 examples/'{}'/main.py
        stage: "test"

  # TODO: Release on VERSION change
  # release:
  #   title: "Release to Pypi"
  #   type: "freestyle" # Run any command
  #   image: "python:3.6.10" # The image in which command will be executed
  #   working_directory: "${{clone}}" # Running command where code cloned
  #   commands:
  #     # Install required packages
  #     - python3 -m pip install --user --upgrade setuptools wheel twine

  #     # Setup Pypi config
  #     - echo "[pypi]" > ~/.pypirc
  #     - echo "repository=https://upload.pypi.org/legacy/" >> ~/.pypirc
  #     - echo "username=${{PYPI_USERNAME}}" >> ~/.pypirc
  #     - echo "password=${{PYPI_PASSWORD}}" >> ~/.pypirc

  #     # Build package
  #     - VERSION_TAG=$(git tag -l --points-at HEAD) python3 setup.py sdist bdist_wheel

  #     # Upload package for distribution
  #     - python3 -m twine upload --repository pypi dist/*
  #   when:
  #     branch:
  #       only:
  #         - /([0-9]+)\.([0-9]+)\.([0-9]+)?$/
  #   stage: "release"
