FROM nvidia/cuda:10.0-cudnn7-runtime
ARG USER_NAME
ARG USER_EMAIL
ARG EXPERIMENT_URL

# Installs necessary dependencies (Python 3, Git, and cURL).
RUN apt-get update && \ 
    apt-get install -y --no-install-recommends \
        curl \
        git \
        python3 \
        python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Installs pip.
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python3 get-pip.py && \
    pip3 install setuptools && \
    rm get-pip.py

# Set the working directory to /app
WORKDIR /app

# Copy requirements.txt from the current directory into the container at /app
COPY requirements-gpu.txt /app

# Install any needed packages specified in requirements.txt
RUN pip3 install --upgrade --trusted-host pypi.python.org -r requirements-gpu.txt

# Copy the current directory contents into the container at /app
COPY . /app

# Setup credentials for google cloud
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json

# Setup global config for experimentation platform
ENV SURROUND_USER_NAME=${{USER_NAME}}
ENV SURROUND_USER_EMAIL=${{USER_EMAIL}}
ENV SURROUND_EXPERIMENT_URL=${{EXPERIMENT_URL}}

# List all tasks when the container launches
ENTRYPOINT ["python3", "-m", "{project_name}"]
