FROM python:3.6.5
ARG USER_NAME
ARG USER_EMAIL
ARG EXPERIMENT_URL

# Set the working directory to /app
WORKDIR /app

# Copy requirements.txt from the current directory into the container at /app
COPY requirements.txt /app

# Install any needed packages specified in requirements.txt
RUN pip3 install --upgrade --trusted-host pypi.python.org -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app

# Setup credentials for google cloud
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json

# Setup global config for experimentation platform
ENV SURROUND_USER_NAME=${{USER_NAME}}
ENV SURROUND_USER_EMAIL=${{USER_EMAIL}}
ENV SURROUND_EXPERIMENT_URL=${{EXPERIMENT_URL}}

# Launch the project when started
ENTRYPOINT ["python3", "-m", "{project_name}"]
