FROM a2i2/testing:latest

RUN pip3 install jupyter -U && pip3 install jupyterlab

EXPOSE 8888

# TODO: Remove token and password settings for production deployment
CMD ["jupyter", "lab","--allow-root", "--ip=0.0.0.0", "--no-browser","--NotebookApp.token=''","--NotebookApp.password=''"]
